name: Deploy

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute update script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: api/script/restart_services.sh
          username: "ec2-user"
          host: "www.osumc-cultural-awareness.com"
          privateKey: ${{ secrets.EC2_SSH_KEY }}